name: Build and Deploy to docs/

on:
  push:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert

      - name: Convert notebooks to HTML
        run: |
          jupyter nbconvert --to html sack_prediction.ipynb --output-dir=docs

      - name: Copy GIFs and assets to docs/
        run: |
          mkdir -p docs
          cp nfl.gif docs/

      - name: Commit and push to docs/
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}
          git add docs/
          git commit -m "Update site content via GitHub Actions" || echo "No changes to commit"
          git remote -v | sed 's/x-access-token:.*/<TOKEN>@github.com/'  # 👈 This should now print the full repo URL
          git push
